DATAOWNER_CONFIG_KEY = "data_owner"
TICKET_SYSTEM_CONFIG_KEY = "access_requests_method"
PROVISION_CONFIG_KEY = "provisioning"
EMAIL_CONFIG_KEY = "email"
COMMUNICATION_CHANNEL_CONFIG_KEY = "communication_channel"
