from typing import Any

from app.llm.tools.user_data.iface import UserAccess, UserDataInterface

data = {
    "1": ["Executive Reporting", "Sprint Planner", "Backlog Manager"],
    "2": ["Code Viewer", "Architecture Access", "Release Manager"],
    "3": ["UX Researcher", "Usability Tester", "Design Contributor"],
    "4": ["Sales Manager", "Contract Negotiator", "Lead Generator"],
    "5": ["Security Audit", "Monitoring Access", "Configuration Editor"],
    "6": ["Deployment Access", "Security Audit", "Global Admin"],
    "7": ["Test Environment Access", "QA Lead", "Release Gatekeeper"],
    "9": ["Marketing Director", "Social Media Manager", "Budget Controller"],
    "10": ["Bug Reporter", "Test Case Editor", "Test Case Viewer"],
    "11": ["Global Admin", "Emergency Response", "Security Audit"],
    "12": ["Global Admin", "Release Manager", "Code Contributor"],
    "13": ["Global Admin", "Test Case Viewer", "Automation Script Access"],
    "14": ["Sprint Planner", "Backlog Manager", "Roadmap Viewer"],
    "15": ["Code Contributor", "Release Manager", "Code Reviewer"],
    "18": ["QA Lead", "Bug Reporter", "Automation Script Access"],
    "19": ["Emergency Response", "Security Audit", "Configuration Editor"],
    "20": ["Infrastructure Admin", "Deployment Access", "Configuration Editor"],
    "21": ["Security Audit", "Configuration Viewer", "Emergency Response"],
    "23": ["Lead Viewer", "Deal Creator", "Executive Deal Approver"],
    "25": ["Bug Reporter", "Test Case Editor", "Release Gatekeeper"],
    "26": ["Code Viewer", "Architecture Access", "Code Contributor"],
    "27": ["Code Contributor", "Code Viewer", "Release Manager"],
    "30": ["Code Viewer", "Architecture Access", "Code Contributor"],
    "32": ["Content Creator", "Marketing Director", "Brand Guardian"],
    "33": ["Feature Requester", "Sprint Planner", "Product Analytics"],
    "34": ["Test Case Viewer", "Global Admin", "Release Gatekeeper"],
    "36": ["Prototype Access", "Usability Tester", "User Feedback Analyst"],
    "38": ["Release Manager", "Code Reviewer", "Code Contributor"],
    "39": ["Recruitment Access", "HR Policy Editor", "Employee Directory"],
    "40": ["Prototype Access", "User Feedback Analyst", "Usability Tester"],
    "41": ["User Feedback Analyst", "Prototype Access", "Design Contributor"],
    "42": ["Compensation Planner", "Performance Review Manager", "Recruitment Access"],
    "43": ["QA Lead", "Test Case Viewer", "Test Environment Access"],
    "47": ["Global Admin", "Release Manager", "Code Contributor"],
    "48": ["Executive Deal Approver", "Lead Viewer", "Sales Manager"],
    "50": ["Code Contributor", "Code Viewer", "Release Manager"],
    "51": ["Employee Directory", "HR Policy Editor", "HRIS Admin"],
    "52": ["HR Policy Editor", "HRIS Admin", "Compensation Planner"],
    "53": ["Bug Reporter", "Automation Script Access", "Test Case Editor"],
    "55": ["Design Contributor", "Design System Admin", "Usability Tester"],
    "56": ["Deal Creator", "Lead Generator", "Sales Manager"],
    "57": ["Bug Reporter", "Global Admin", "Automation Script Access"],
    "58": ["Executive Deal Approver", "Lead Viewer", "Deal Creator"],
    "62": ["Compensation Planner", "Performance Review Manager", "HR Policy Editor"],
    "64": ["Compensation Planner", "HR Policy Editor", "Employee Relations"],
    "65": ["Monitoring Access", "Deployment Access", "Configuration Viewer"],
    "66": ["Release Gatekeeper", "Test Case Editor", "Bug Reporter"],
    "67": ["HR Policy Editor", "Compensation Planner", "HRIS Admin"],
    "68": ["Content Creator", "Budget Controller", "Brand Guardian"],
    "69": ["Executive Reporting", "Stakeholder Communicator", "Roadmap Viewer"],
    "70": ["Deal Creator", "Executive Deal Approver", "Lead Generator"],
    "71": ["Infrastructure Admin", "Global Admin", "Configuration Viewer"],
    "72": ["HRIS Admin", "HR Policy Editor", "Recruitment Access"],
    "73": ["Configuration Editor", "Deployment Access", "Global Admin"],
    "74": ["Executive Reporting", "Feature Requester", "Backlog Manager"],
    "75": ["Release Manager", "Code Contributor", "Global Admin"],
    "76": ["Release Manager", "Code Reviewer", "Code Viewer"],
    "77": ["Deal Creator", "Executive Deal Approver", "Sales Manager"],
    "80": ["Recruitment Access", "HRIS Admin", "Employee Relations"],
    "82": ["Deployment Access", "Configuration Editor", "Security Audit"],
    "83": ["UX Researcher", "User Feedback Analyst", "Usability Tester"],
    "84": ["Roadmap Viewer", "Feature Requester", "Product Analytics"],
    "85": ["Employee Directory", "HR Policy Editor", "Compensation Planner"],
    "86": ["Test Case Viewer", "Test Environment Access", "Release Gatekeeper"],
    "87": ["Architecture Access", "Code Contributor", "Release Manager"],
    "88": ["Feature Requester", "Product Analytics", "Roadmap Viewer"],
    "90": ["Commission Reporter", "Sales Manager", "Lead Viewer"],
    "91": ["Release Gatekeeper", "Test Environment Access", "Global Admin"],
    "92": ["Bug Reporter", "Test Case Viewer", "Test Case Editor"],
    "94": ["Infrastructure Admin", "Configuration Viewer", "Emergency Response"],
    "96": ["Code Reviewer", "Global Admin", "Code Contributor"],
    "97": ["Usability Tester", "Prototype Access", "Design Contributor"],
    "98": ["Analytics Viewer", "Brand Guardian", "Budget Controller"],
    "100": ["HR Policy Editor", "Employee Relations", "HRIS Admin"],
    "101": ["Configuration Editor", "Monitoring Access", "Infrastructure Admin"],
    "102": ["Usability Tester", "Prototype Access", "User Feedback Analyst"],
    "105": ["Recruitment Access", "HRIS Admin", "Performance Review Manager"],
    "107": ["Compensation Planner", "HR Policy Editor", "HRIS Admin"],
    "108": ["Code Contributor", "Release Manager", "Code Reviewer"],
    "110": ["Recruitment Access", "Employee Relations", "Compensation Planner"],
    "111": ["Code Reviewer", "Global Admin", "Code Contributor"],
    "112": ["Emergency Response", "Deployment Access", "Global Admin"],
    "113": ["Code Reviewer", "Architecture Access", "Code Contributor"],
    "115": ["Release Manager", "Code Contributor", "Code Reviewer"],
    "116": ["Marketing Director", "Budget Controller", "Brand Guardian"],
    "117": ["Feature Requester", "Product Analytics", "Executive Reporting"],
    "118": ["Sprint Planner", "Stakeholder Communicator", "Backlog Manager"],
    "119": ["Design Viewer", "Design Contributor", "UX Researcher"],
    "121": ["Code Contributor", "Code Viewer", "Code Reviewer"],
    "123": ["Architecture Access", "Code Viewer", "Code Contributor"],
    "124": ["Lead Generator", "Lead Viewer", "Contract Negotiator"],
    "125": ["Feature Requester", "Backlog Manager", "Executive Reporting"],
    "126": ["Performance Review Manager", "Recruitment Access", "Employee Relations"],
    "127": ["Sales Manager", "Commission Reporter", "Executive Deal Approver"],
    "129": ["Marketing Director", "Campaign Viewer", "Brand Guardian"],
    "131": ["Sprint Planner", "Stakeholder Communicator", "Product Analytics"],
    "132": ["Design System Admin", "UX Researcher", "User Feedback Analyst"],
    "133": ["Security Audit", "Configuration Viewer", "Configuration Editor"],
    "134": ["Test Environment Access", "QA Lead", "Release Gatekeeper"],
    "136": ["Recruitment Access", "Employee Directory", "HRIS Admin"],
    "137": ["Emergency Response", "Monitoring Access", "Security Audit"],
    "141": ["QA Lead", "Automation Script Access", "Test Environment Access"],
    "142": ["Lead Viewer", "Lead Generator", "Executive Deal Approver"],
    "143": ["Release Manager", "Code Contributor", "Architecture Access"],
    "144": ["Stakeholder Communicator", "Roadmap Viewer", "Product Analytics"],
    "147": ["Stakeholder Communicator", "Roadmap Viewer", "Product Analytics"],
    "149": ["Campaign Viewer", "Budget Controller", "Social Media Manager"],
    "150": ["Design System Admin", "Design Contributor", "Usability Tester"],
    "151": ["Performance Review Manager", "HR Policy Editor", "Compensation Planner"],
    "153": ["Code Contributor", "Global Admin", "Code Viewer"],
    "154": ["Design Viewer", "User Feedback Analyst", "Design Contributor"],
    "157": ["Prototype Access", "Design Viewer", "User Feedback Analyst"],
    "160": ["Architecture Access", "Global Admin", "Code Reviewer"],
    "161": ["Campaign Viewer", "Marketing Director", "Brand Guardian"],
    "162": ["Deal Creator", "Commission Reporter", "Executive Deal Approver"],
    "163": ["Commission Reporter", "Sales Manager", "Contract Negotiator"],
    "166": ["Code Reviewer", "Release Manager", "Code Viewer"],
    "167": ["Deployment Access", "Configuration Viewer", "Emergency Response"],
    "168": ["Analytics Viewer", "Content Creator", "Social Media Manager"],
    "169": ["Security Audit", "Configuration Viewer", "Configuration Editor"],
    "170": ["Test Case Viewer", "Test Case Editor", "Bug Reporter"],
    "172": ["UX Researcher", "Prototype Access", "Design Contributor"],
    "173": ["Sales Manager", "Commission Reporter", "Lead Viewer"],
    "174": ["Code Reviewer", "Architecture Access", "Global Admin"],
    "175": ["Code Contributor", "Global Admin", "Code Viewer"],
    "176": ["Campaign Viewer", "Budget Controller", "Marketing Director"],
    "177": ["Code Viewer", "Code Contributor", "Code Reviewer"],
    "178": ["Global Admin", "Release Gatekeeper", "Test Environment Access"],
    "181": ["Global Admin", "Release Gatekeeper", "QA Lead"],
    "182": ["Monitoring Access", "Deployment Access", "Configuration Editor"],
    "183": ["Code Viewer", "Code Contributor", "Architecture Access"],
    "184": ["Compensation Planner", "Performance Review Manager", "Recruitment Access"],
    "185": ["Automation Script Access", "QA Lead", "Test Environment Access"],
    "187": ["Contract Negotiator", "Lead Viewer", "Executive Deal Approver"],
    "188": ["Code Reviewer", "Architecture Access", "Global Admin"],
    "190": ["Sales Manager", "Lead Viewer", "Lead Generator"],
    "191": ["Configuration Editor", "Security Audit", "Global Admin"],
    "192": ["Deal Creator", "Sales Manager", "Lead Generator"],
    "193": ["Lead Viewer", "Sales Manager", "Executive Deal Approver"],
    "195": ["Bug Reporter", "Test Case Viewer", "Automation Script Access"],
    "197": ["Security Audit", "Infrastructure Admin", "Emergency Response"],
    "198": ["Code Contributor", "Architecture Access", "Code Reviewer"],
    "200": ["Recruitment Access", "HR Policy Editor", "Employee Directory"],
    "201": ["Social Media Manager", "Budget Controller", "Content Creator"],
    "202": ["Campaign Viewer", "Analytics Viewer", "Marketing Director"],
    "203": ["UX Researcher", "Usability Tester", "Design Contributor"],
    "207": ["Release Manager", "Code Reviewer", "Architecture Access"],
    "208": ["Product Analytics", "Executive Reporting", "Backlog Manager"],
    "209": ["Bug Reporter", "QA Lead", "Global Admin"],
    "211": ["Content Creator", "Campaign Viewer", "Marketing Director"],
    "212": ["Bug Reporter", "Release Gatekeeper", "Test Case Viewer"],
    "213": ["User Feedback Analyst", "Design Contributor", "Prototype Access"],
    "214": ["Architecture Access", "Release Manager", "Code Reviewer"],
    "215": ["Global Admin", "Emergency Response", "Infrastructure Admin"],
    "220": ["Security Audit", "Monitoring Access", "Global Admin"],
    "221": ["Lead Viewer", "Sales Manager", "Lead Generator"],
    "223": ["Global Admin", "Infrastructure Admin", "Monitoring Access"],
    "224": ["Code Contributor", "Code Viewer", "Global Admin"],
    "225": ["Architecture Access", "Global Admin", "Code Contributor"],
    "227": ["Code Reviewer", "Global Admin", "Release Manager"],
    "228": ["Code Reviewer", "Global Admin", "Release Manager"],
    "229": ["Code Viewer", "Global Admin", "Code Reviewer"],
    "231": ["Brand Guardian", "Marketing Director", "Social Media Manager"],
    "232": ["Employee Directory", "Performance Review Manager", "Recruitment Access"],
    "233": ["Test Case Editor", "QA Lead", "Test Environment Access"],
    "234": ["Code Viewer", "Architecture Access", "Release Manager"],
    "235": ["Code Reviewer", "Release Manager", "Code Viewer"],
    "236": ["Design Viewer", "Prototype Access", "User Feedback Analyst"],
    "237": ["Design Contributor", "Prototype Access", "UX Researcher"],
    "238": ["Lead Viewer", "Deal Creator", "Lead Generator"],
    "240": ["Release Manager", "Code Contributor", "Global Admin"],
    "241": ["Contract Negotiator", "Lead Viewer", "Lead Generator"],
    "242": ["Release Manager", "Global Admin", "Architecture Access"],
    "243": ["Global Admin", "Code Contributor", "Code Reviewer"],
    "244": ["User Feedback Analyst", "Usability Tester", "Prototype Access"],
    "245": ["Release Manager", "Architecture Access", "Code Reviewer"],
    "247": ["Test Environment Access", "Global Admin", "Bug Reporter"],
    "248": ["Code Contributor", "Code Viewer", "Architecture Access"],
    "249": ["Contract Negotiator", "Deal Creator", "Executive Deal Approver"],
    "250": ["Brand Guardian", "Content Creator", "Marketing Director"],
    "251": ["Usability Tester", "Design Viewer", "Design System Admin"],
    "252": ["Stakeholder Communicator", "Backlog Manager", "Feature Requester"],
    "254": ["Architecture Access", "Code Contributor", "Code Reviewer"],
    "256": ["Release Gatekeeper", "Test Case Editor", "Test Case Viewer"],
    "259": ["Lead Viewer", "Commission Reporter", "Deal Creator"],
    "260": ["HRIS Admin", "Compensation Planner", "HR Policy Editor"],
    "261": ["Usability Tester", "Prototype Access", "Design Viewer"],
    "262": ["Compensation Planner", "HR Policy Editor", "Recruitment Access"],
    "264": ["Feature Requester", "Roadmap Viewer", "Sprint Planner"],
    "265": ["Product Analytics", "Stakeholder Communicator", "Executive Reporting"],
    "266": ["Product Analytics", "Backlog Manager", "Executive Reporting"],
    "267": ["Automation Script Access", "QA Lead", "Global Admin"],
    "268": ["Emergency Response", "Configuration Editor", "Infrastructure Admin"],
    "269": ["Configuration Viewer", "Emergency Response", "Monitoring Access"],
    "270": ["Release Manager", "Code Reviewer", "Code Viewer"],
    "271": ["HR Policy Editor", "HRIS Admin", "Performance Review Manager"],
    "272": ["Social Media Manager", "Analytics Viewer", "Marketing Director"],
    "273": ["Brand Guardian", "Budget Controller", "Marketing Director"],
    "274": ["Roadmap Viewer", "Backlog Manager", "Feature Requester"],
    "276": ["Brand Guardian", "Budget Controller", "Content Creator"],
    "277": ["Employee Directory", "Compensation Planner", "Employee Relations"],
    "278": ["Emergency Response", "Monitoring Access", "Configuration Viewer"],
    "279": ["Bug Reporter", "Global Admin", "QA Lead"],
    "280": ["Test Case Editor", "Global Admin", "Release Gatekeeper"],
    "283": ["Prototype Access", "UX Researcher", "Usability Tester"],
    "285": ["Lead Generator", "Lead Viewer", "Contract Negotiator"],
    "286": ["Deployment Access", "Configuration Viewer", "Infrastructure Admin"],
    "287": ["Code Reviewer", "Architecture Access", "Code Viewer"],
    "288": ["Usability Tester", "Design Contributor", "User Feedback Analyst"],
    "289": ["Security Audit", "Emergency Response", "Global Admin"],
    "290": ["Release Gatekeeper", "Test Environment Access", "QA Lead"],
    "291": ["Security Audit", "Infrastructure Admin", "Deployment Access"],
    "292": ["Usability Tester", "Prototype Access", "User Feedback Analyst"],
    "294": ["Campaign Viewer", "Social Media Manager", "Brand Guardian"],
    "295": ["Lead Generator", "Lead Viewer", "Deal Creator"],
    "296": ["Compensation Planner", "Employee Relations", "Recruitment Access"],
    "297": ["Design Contributor", "Prototype Access", "Design Viewer"],
    "298": ["Test Case Viewer", "Test Environment Access", "Release Gatekeeper"],
    "300": ["User Feedback Analyst", "Design Contributor", "Design Viewer"],
    "301": ["Test Environment Access", "Release Gatekeeper", "Test Case Viewer"],
    "302": ["Configuration Viewer", "Configuration Editor", "Global Admin"],
    "304": ["Feature Requester", "Backlog Manager", "Product Analytics"],
    "305": ["Prototype Access", "Usability Tester", "User Feedback Analyst"],
    "306": ["Usability Tester", "Design Viewer", "Prototype Access"],
    "307": ["User Feedback Analyst", "Design Contributor", "Prototype Access"],
    "308": ["Code Reviewer", "Release Manager", "Code Contributor"],
    "309": ["Code Reviewer", "Architecture Access", "Global Admin"],
    "310": ["Analytics Viewer", "Campaign Viewer", "Budget Controller"],
    "311": ["Code Contributor", "Code Reviewer", "Global Admin"],
    "312": ["Code Viewer", "Global Admin", "Code Reviewer"],
    "313": ["Stakeholder Communicator", "Feature Requester", "Product Analytics"],
    "314": ["Configuration Viewer", "Deployment Access", "Infrastructure Admin"],
    "315": ["Compensation Planner", "Employee Relations", "Performance Review Manager"],
    "316": ["Test Case Editor", "Automation Script Access", "Bug Reporter"],
    "317": ["Code Contributor", "Code Viewer", "Code Reviewer"],
    "320": ["Performance Review Manager", "Employee Relations", "HR Policy Editor"],
    "321": ["Test Case Editor", "Test Environment Access", "Bug Reporter"],
    "322": ["Test Case Viewer", "Global Admin", "QA Lead"],
    "323": ["Prototype Access", "Design System Admin", "User Feedback Analyst"],
    "324": ["User Feedback Analyst", "Design Viewer", "Prototype Access"],
    "325": ["Compensation Planner", "Performance Review Manager", "Employee Directory"],
    "326": ["Global Admin", "Code Reviewer", "Release Manager"],
    "327": ["Lead Generator", "Deal Creator", "Sales Manager"],
    "328": ["Global Admin", "Code Contributor", "Architecture Access"],
    "332": ["Marketing Director", "Analytics Viewer", "Brand Guardian"],
    "333": ["Roadmap Viewer", "Product Analytics", "Sprint Planner"],
    "334": ["Usability Tester", "Design Contributor", "UX Researcher"],
    "336": ["Employee Relations", "Recruitment Access", "Performance Review Manager"],
    "337": ["Global Admin", "Code Viewer", "Release Manager"],
    "338": ["QA Lead", "Test Case Viewer", "Test Environment Access"],
    "339": ["Automation Script Access", "Test Environment Access", "Test Case Viewer"],
    "340": ["Social Media Manager", "Analytics Viewer", "Brand Guardian"],
    "343": ["Performance Review Manager", "Employee Directory", "Compensation Planner"],
    "345": ["Executive Deal Approver", "Contract Negotiator", "Commission Reporter"],
    "347": ["Code Reviewer", "Code Viewer", "Release Manager"],
    "348": ["Code Contributor", "Code Reviewer", "Architecture Access"],
    "349": ["Global Admin", "Code Contributor", "Architecture Access"],
    "352": ["Release Manager", "Global Admin", "Code Contributor"],
    "353": ["Lead Generator", "Executive Deal Approver", "Deal Creator"],
    "354": ["Sales Manager", "Lead Viewer", "Contract Negotiator"],
    "355": ["Usability Tester", "Design Contributor", "UX Researcher"],
    "356": ["Lead Generator", "Commission Reporter", "Deal Creator"],
    "357": ["Code Contributor", "Global Admin", "Code Reviewer"],
    "358": ["Code Reviewer", "Code Contributor", "Release Manager"],
    "360": ["Budget Controller", "Content Creator", "Marketing Director"],
    "362": ["Global Admin", "Code Viewer", "Architecture Access"],
    "364": ["Commission Reporter", "Lead Viewer", "Sales Manager"],
    "365": ["Code Reviewer", "Code Contributor", "Global Admin"],
    "367": ["Usability Tester", "Design Viewer", "Prototype Access"],
    "369": ["Monitoring Access", "Configuration Editor", "Deployment Access"],
    "370": ["Release Gatekeeper", "Test Case Viewer", "Test Environment Access"],
    "371": ["Content Creator", "Analytics Viewer", "Social Media Manager"],
    "373": ["Performance Review Manager", "HR Policy Editor", "Employee Directory"],
    "375": ["Emergency Response", "Monitoring Access", "Deployment Access"],
    "376": ["Code Viewer", "Code Reviewer", "Global Admin"],
    "379": ["Global Admin", "Release Gatekeeper", "QA Lead"],
    "380": ["Bug Reporter", "QA Lead", "Test Environment Access"],
    "381": ["Test Case Viewer", "Test Environment Access", "Automation Script Access"],
    "383": ["Test Environment Access", "Bug Reporter", "Test Case Editor"],
    "384": ["Brand Guardian", "Budget Controller", "Campaign Viewer"],
    "387": ["Code Viewer", "Architecture Access", "Code Contributor"],
    "389": ["Test Environment Access", "Release Gatekeeper", "Test Case Viewer"],
    "390": ["HR Policy Editor", "HRIS Admin", "Employee Directory"],
    "391": ["Recruitment Access", "Performance Review Manager", "HRIS Admin"],
    "392": ["Backlog Manager", "Feature Requester", "Product Analytics"],
    "393": ["Executive Reporting", "Roadmap Viewer", "Product Analytics"],
    "395": ["Security Audit", "Global Admin", "Monitoring Access"],
    "396": ["Performance Review Manager", "Recruitment Access", "HRIS Admin"],
    "398": ["Employee Directory", "Compensation Planner", "Employee Relations"],
    "400": ["User Feedback Analyst", "Design Contributor", "Usability Tester"],
    "401": ["Employee Directory", "HRIS Admin", "Recruitment Access"],
    "403": ["HR Policy Editor", "Performance Review Manager", "Employee Directory"],
    "407": ["Budget Controller", "Social Media Manager", "Marketing Director"],
    "408": ["QA Lead", "Automation Script Access", "Release Gatekeeper"],
    "409": ["Release Manager", "Code Contributor", "Architecture Access"],
    "410": ["Design Contributor", "Prototype Access", "Design System Admin"],
    "411": ["Contract Negotiator", "Commission Reporter", "Deal Creator"],
    "412": ["Test Case Viewer", "QA Lead", "Test Environment Access"],
    "413": ["Content Creator", "Budget Controller", "Marketing Director"],
    "415": ["Lead Viewer", "Lead Generator", "Deal Creator"],
    "418": ["Code Reviewer", "Architecture Access", "Code Viewer"],
    "419": ["Configuration Viewer", "Monitoring Access", "Infrastructure Admin"],
    "420": ["Feature Requester", "Roadmap Viewer", "Product Analytics"],
    "421": ["Employee Relations", "HRIS Admin", "Employee Directory"],
    "422": ["Code Reviewer", "Code Contributor", "Architecture Access"],
    "424": ["Employee Relations", "Employee Directory", "Recruitment Access"],
    "425": ["Emergency Response", "Configuration Editor", "Deployment Access"],
    "428": ["Bug Reporter", "Release Gatekeeper", "Test Environment Access"],
    "430": ["User Feedback Analyst", "Design Viewer", "UX Researcher"],
    "432": ["Global Admin", "Code Viewer", "Code Reviewer"],
    "433": ["Emergency Response", "Monitoring Access", "Configuration Viewer"],
    "434": ["User Feedback Analyst", "Prototype Access", "Usability Tester"],
    "436": ["Infrastructure Admin", "Security Audit", "Emergency Response"],
    "437": ["Commission Reporter", "Contract Negotiator", "Executive Deal Approver"],
    "441": ["Global Admin", "Configuration Editor", "Deployment Access"],
    "443": ["Roadmap Viewer", "Stakeholder Communicator", "Executive Reporting"],
    "444": ["Global Admin", "Release Manager", "Code Contributor"],
    "445": ["Prototype Access", "UX Researcher", "Design System Admin"],
    "446": ["Code Contributor", "Code Reviewer", "Release Manager"],
    "447": ["Security Audit", "Global Admin", "Infrastructure Admin"],
    "448": ["Monitoring Access", "Emergency Response", "Deployment Access"],
    "449": ["Stakeholder Communicator", "Sprint Planner", "Executive Reporting"],
    "450": ["Architecture Access", "Code Viewer", "Code Contributor"],
    "452": ["Commission Reporter", "Lead Viewer", "Sales Manager"],
    "453": ["QA Lead", "Test Case Editor", "Release Gatekeeper"],
    "454": ["Code Viewer", "Global Admin", "Code Contributor"],
    "456": ["Architecture Access", "Code Reviewer", "Code Viewer"],
    "457": ["Performance Review Manager", "Employee Relations", "Recruitment Access"],
    "458": ["HR Policy Editor", "Employee Relations", "HRIS Admin"],
    "459": ["Release Gatekeeper", "Automation Script Access", "Test Case Editor"],
    "461": ["Emergency Response", "Infrastructure Admin", "Global Admin"],
    "464": ["User Feedback Analyst", "Prototype Access", "Design System Admin"],
    "467": ["Social Media Manager", "Analytics Viewer", "Brand Guardian"],
    "468": ["Prototype Access", "Usability Tester", "Design System Admin"],
    "469": ["Infrastructure Admin", "Configuration Editor", "Emergency Response"],
    "470": ["Stakeholder Communicator", "Product Analytics", "Executive Reporting"],
    "472": ["Code Contributor", "Release Manager", "Architecture Access"],
    "473": ["Code Contributor", "Release Manager", "Global Admin"],
    "475": ["Code Contributor", "Release Manager", "Code Reviewer"],
    "476": ["Stakeholder Communicator", "Executive Reporting", "Sprint Planner"],
    "477": ["Test Case Editor", "Bug Reporter", "Release Gatekeeper"],
    "478": ["Product Analytics", "Sprint Planner", "Backlog Manager"],
    "479": ["Emergency Response", "Configuration Editor", "Infrastructure Admin"],
    "480": ["Test Case Viewer", "Automation Script Access", "QA Lead"],
    "482": ["Test Environment Access", "QA Lead", "Automation Script Access"],
    "483": ["User Feedback Analyst", "Prototype Access", "Design Viewer"],
    "484": ["Social Media Manager", "Brand Guardian", "Campaign Viewer"],
    "485": ["Analytics Viewer", "Budget Controller", "Content Creator"],
    "486": ["Contract Negotiator", "Deal Creator", "Lead Viewer"],
    "487": ["Design System Admin", "User Feedback Analyst", "Design Viewer"],
    "488": ["Design System Admin", "UX Researcher", "Design Contributor"],
    "489": ["Budget Controller", "Analytics Viewer", "Content Creator"],
    "490": ["Deal Creator", "Executive Deal Approver", "Lead Viewer"],
    "491": ["Code Contributor", "Architecture Access", "Code Viewer"],
    "492": ["Budget Controller", "Social Media Manager", "Analytics Viewer"],
    "493": ["Design Viewer", "Prototype Access", "Usability Tester"],
    "494": ["Global Admin", "QA Lead", "Test Case Viewer"],
    "495": ["Roadmap Viewer", "Stakeholder Communicator", "Feature Requester"],
    "496": ["Test Environment Access", "Global Admin", "Test Case Editor"],
    "497": ["Monitoring Access", "Deployment Access", "Configuration Viewer"],
    "499": ["Global Admin", "Architecture Access", "Code Viewer"],
    "502": ["Content Creator", "Marketing Director", "Campaign Viewer"],
    "503": ["Stakeholder Communicator", "Roadmap Viewer", "Executive Reporting"],
    "504": ["UX Researcher", "Design Contributor", "Usability Tester"],
    "507": ["Release Manager", "Architecture Access", "Code Viewer"],
    "508": ["Security Audit", "Deployment Access", "Global Admin"],
    "509": ["Performance Review Manager", "Recruitment Access", "Employee Relations"],
    "510": ["Employee Directory", "Compensation Planner", "Recruitment Access"],
    "511": ["Security Audit", "Configuration Editor", "Global Admin"],
    "512": ["Deal Creator", "Executive Deal Approver", "Lead Viewer"],
    "513": ["QA Lead", "Test Environment Access", "Bug Reporter"],
    "514": ["UX Researcher", "User Feedback Analyst", "Design System Admin"],
    "515": ["Social Media Manager", "Content Creator", "Analytics Viewer"],
    "516": ["Code Viewer", "Code Contributor", "Release Manager"],
    "517": ["Budget Controller", "Social Media Manager", "Content Creator"],
    "518": ["Deal Creator", "Lead Viewer", "Sales Manager"],
    "519": ["Test Case Viewer", "Test Environment Access", "QA Lead"],
    "522": ["Infrastructure Admin", "Emergency Response", "Configuration Viewer"],
    "524": ["Deployment Access", "Emergency Response", "Monitoring Access"],
    "525": ["Sprint Planner", "Executive Reporting", "Feature Requester"],
    "528": ["Design System Admin", "Usability Tester", "Prototype Access"],
    "529": ["Design System Admin", "UX Researcher", "Design Contributor"],
    "530": ["Lead Viewer", "Sales Manager", "Deal Creator"],
    "533": ["Global Admin", "Architecture Access", "Code Contributor"],
    "534": ["Infrastructure Admin", "Global Admin", "Configuration Editor"],
    "535": ["User Feedback Analyst", "Design Viewer", "Prototype Access"],
    "536": ["Code Viewer", "Global Admin", "Release Manager"],
    "537": ["Brand Guardian", "Analytics Viewer", "Social Media Manager"],
    "538": ["Architecture Access", "Code Viewer", "Code Reviewer"],
    "539": ["Sales Manager", "Executive Deal Approver", "Commission Reporter"],
    "540": ["Bug Reporter", "Test Environment Access", "Global Admin"],
    "541": ["Test Environment Access", "Release Gatekeeper", "Bug Reporter"],
    "543": ["Code Contributor", "Architecture Access", "Code Reviewer"],
    "544": ["Infrastructure Admin", "Configuration Editor", "Emergency Response"],
    "548": ["Code Contributor", "Architecture Access", "Code Reviewer"],
    "549": ["Global Admin", "Code Reviewer", "Release Manager"],
    "550": ["Employee Relations", "HR Policy Editor", "Employee Directory"],
    "552": ["Roadmap Viewer", "Backlog Manager", "Product Analytics"],
    "553": ["Code Reviewer", "Code Contributor", "Architecture Access"],
    "554": ["Campaign Viewer", "Content Creator", "Marketing Director"],
    "555": ["Design System Admin", "Design Contributor", "Prototype Access"],
    "556": ["Employee Relations", "Employee Directory", "Compensation Planner"],
    "557": ["Employee Relations", "HRIS Admin", "Performance Review Manager"],
    "558": ["Test Case Editor", "Test Case Viewer", "QA Lead"],
    "561": ["UX Researcher", "Design Contributor", "Design Viewer"],
    "562": ["Feature Requester", "Sprint Planner", "Backlog Manager"],
    "563": ["Feature Requester", "Backlog Manager", "Roadmap Viewer"],
    "564": ["Design Contributor", "Design System Admin", "Prototype Access"],
    "565": ["Brand Guardian", "Social Media Manager", "Content Creator"],
    "566": ["Code Reviewer", "Code Contributor", "Architecture Access"],
    "567": ["Architecture Access", "Release Manager", "Code Contributor"],
    "568": ["Architecture Access", "Code Viewer", "Release Manager"],
    "569": ["Executive Deal Approver", "Lead Viewer", "Deal Creator"],
    "570": ["Release Manager", "Code Viewer", "Architecture Access"],
    "571": ["Code Contributor", "Architecture Access", "Code Reviewer"],
    "572": ["Design Viewer", "Design Contributor", "User Feedback Analyst"],
    "573": ["Deployment Access", "Infrastructure Admin", "Global Admin"],
    "575": ["Performance Review Manager", "HR Policy Editor", "Employee Relations"],
    "576": ["Campaign Viewer", "Marketing Director", "Social Media Manager"],
    "577": ["Backlog Manager", "Feature Requester", "Stakeholder Communicator"],
    "578": ["Code Viewer", "Release Manager", "Code Contributor"],
    "579": ["Lead Generator", "Lead Viewer", "Executive Deal Approver"],
    "580": ["Architecture Access", "Code Reviewer", "Code Contributor"],
    "581": ["Deal Creator", "Commission Reporter", "Sales Manager"],
    "583": ["Code Contributor", "Code Viewer", "Release Manager"],
    "584": ["Code Reviewer", "Architecture Access", "Release Manager"],
    "586": ["QA Lead", "Bug Reporter", "Automation Script Access"],
    "588": ["Release Manager", "Global Admin", "Architecture Access"],
    "589": ["Usability Tester", "Prototype Access", "User Feedback Analyst"],
    "591": ["Code Contributor", "Code Reviewer", "Global Admin"],
    "592": ["UX Researcher", "Design Viewer", "Prototype Access"],
    "593": ["Campaign Viewer", "Marketing Director", "Content Creator"],
    "594": ["Global Admin", "Code Viewer", "Code Contributor"],
    "595": ["Code Contributor", "Global Admin", "Code Reviewer"],
    "596": ["Social Media Manager", "Budget Controller", "Analytics Viewer"],
    "597": ["Code Reviewer", "Code Viewer", "Architecture Access"],
    "598": ["Release Manager", "Architecture Access", "Code Reviewer"],
    "599": ["Executive Reporting", "Feature Requester", "Sprint Planner"],
    "600": ["Prototype Access", "UX Researcher", "Design Contributor"],
    "601": ["Sales Manager", "Executive Deal Approver", "Lead Viewer"],
    "602": ["Code Reviewer", "Release Manager", "Code Contributor"],
    "603": ["Analytics Viewer", "Social Media Manager", "Content Creator"],
    "605": ["Employee Relations", "Compensation Planner", "Recruitment Access"],
    "606": ["Backlog Manager", "Stakeholder Communicator", "Sprint Planner"],
    "607": ["Budget Controller", "Content Creator", "Analytics Viewer"],
    "608": ["Test Case Editor", "Release Gatekeeper", "Bug Reporter"],
    "609": ["Analytics Viewer", "Campaign Viewer", "Content Creator"],
    "610": ["Design Contributor", "Usability Tester", "UX Researcher"],
    "611": ["Release Manager", "Code Contributor", "Code Reviewer"],
    "612": ["Emergency Response", "Configuration Editor", "Infrastructure Admin"],
    "613": ["Sales Manager", "Executive Deal Approver", "Deal Creator"],
    "615": ["Recruitment Access", "Employee Directory", "Compensation Planner"],
    "616": ["Code Reviewer", "Code Viewer", "Architecture Access"],
    "618": ["Infrastructure Admin", "Security Audit", "Emergency Response"],
    "621": ["Employee Directory", "HR Policy Editor", "Performance Review Manager"],
    "623": ["HRIS Admin", "HR Policy Editor", "Performance Review Manager"],
    "624": ["Deployment Access", "Configuration Editor", "Emergency Response"],
    "625": ["Brand Guardian", "Content Creator", "Marketing Director"],
    "626": ["Code Contributor", "Architecture Access", "Code Viewer"],
    "628": ["Code Viewer", "Code Reviewer", "Code Contributor"],
    "629": ["Code Contributor", "Code Reviewer", "Release Manager"],
    "632": ["Release Manager", "Architecture Access", "Code Reviewer"],
    "633": ["Release Manager", "Architecture Access", "Code Viewer"],
    "634": ["Employee Directory", "Compensation Planner", "HR Policy Editor"],
    "635": ["Code Contributor", "Architecture Access", "Release Manager"],
    "637": ["Backlog Manager", "Feature Requester", "Sprint Planner"],
    "638": ["Global Admin", "Deployment Access", "Configuration Viewer"],
    "639": ["Global Admin", "Code Viewer", "Code Reviewer"],
    "640": ["Code Contributor", "Code Viewer", "Architecture Access"],
    "641": ["Brand Guardian", "Campaign Viewer", "Budget Controller"],
    "643": [
        "Automation Script Access",
        "Release Gatekeeper",
        "Test Environment Access",
    ],
    "644": ["Roadmap Viewer", "Executive Reporting", "Backlog Manager"],
    "645": ["Code Viewer", "Global Admin", "Code Reviewer"],
    "646": ["Deal Creator", "Lead Generator", "Contract Negotiator"],
    "647": ["Bug Reporter", "QA Lead", "Automation Script Access"],
    "649": ["Configuration Editor", "Infrastructure Admin", "Configuration Viewer"],
    "651": ["Stakeholder Communicator", "Product Analytics", "Executive Reporting"],
    "652": ["Usability Tester", "UX Researcher", "Design Viewer"],
    "653": ["Usability Tester", "Design Viewer", "Prototype Access"],
    "654": ["Global Admin", "Configuration Viewer", "Security Audit"],
    "655": ["Contract Negotiator", "Commission Reporter", "Lead Viewer"],
    "657": ["Code Reviewer", "Code Viewer", "Code Contributor"],
    "658": ["Prototype Access", "Usability Tester", "Design System Admin"],
    "659": ["Emergency Response", "Deployment Access", "Security Audit"],
    "661": ["Global Admin", "Test Case Editor", "QA Lead"],
    "662": ["Content Creator", "Campaign Viewer", "Budget Controller"],
    "663": ["Test Case Viewer", "Test Environment Access", "Global Admin"],
    "664": ["Executive Deal Approver", "Lead Viewer", "Deal Creator"],
    "666": ["Architecture Access", "Code Viewer", "Global Admin"],
    "667": ["Content Creator", "Budget Controller", "Brand Guardian"],
    "668": ["Performance Review Manager", "Employee Directory", "HRIS Admin"],
    "671": ["Code Viewer", "Code Reviewer", "Release Manager"],
    "674": ["Code Reviewer", "Code Contributor", "Code Viewer"],
    "676": ["Monitoring Access", "Configuration Viewer", "Global Admin"],
    "679": ["Architecture Access", "Code Contributor", "Code Reviewer"],
    "680": ["Campaign Viewer", "Analytics Viewer", "Social Media Manager"],
    "681": ["Code Viewer", "Code Reviewer", "Code Contributor"],
    "683": ["Brand Guardian", "Analytics Viewer", "Budget Controller"],
    "684": ["Release Manager", "Architecture Access", "Global Admin"],
    "685": ["Test Case Editor", "Release Gatekeeper", "Test Case Viewer"],
    "687": ["Test Case Viewer", "Release Gatekeeper", "Test Case Editor"],
    "689": ["Release Gatekeeper", "Test Case Editor", "Test Environment Access"],
    "691": ["Code Reviewer", "Code Contributor", "Global Admin"],
    "692": ["Architecture Access", "Code Reviewer", "Global Admin"],
    "693": ["Automation Script Access", "Global Admin", "Test Environment Access"],
    "694": ["Design Contributor", "Prototype Access", "Design System Admin"],
    "695": ["Infrastructure Admin", "Emergency Response", "Deployment Access"],
    "696": ["HR Policy Editor", "HRIS Admin", "Employee Directory"],
    "697": ["Sprint Planner", "Product Analytics", "Roadmap Viewer"],
    "698": ["Design Viewer", "Usability Tester", "Design Contributor"],
    "699": ["Contract Negotiator", "Lead Viewer", "Executive Deal Approver"],
    "701": ["Budget Controller", "Analytics Viewer", "Content Creator"],
    "703": ["HR Policy Editor", "HRIS Admin", "Performance Review Manager"],
    "705": ["Analytics Viewer", "Marketing Director", "Campaign Viewer"],
    "707": ["Automation Script Access", "Test Case Viewer", "Global Admin"],
    "708": ["Code Contributor", "Code Viewer", "Code Reviewer"],
    "710": ["Design System Admin", "Design Viewer", "Usability Tester"],
    "711": ["HR Policy Editor", "Recruitment Access", "Employee Relations"],
    "712": ["Global Admin", "Release Gatekeeper", "Bug Reporter"],
    "714": ["HR Policy Editor", "Compensation Planner", "Performance Review Manager"],
    "716": ["Design Viewer", "Usability Tester", "Prototype Access"],
    "717": ["Release Manager", "Code Viewer", "Architecture Access"],
    "721": ["Sales Manager", "Lead Generator", "Deal Creator"],
    "722": ["Release Gatekeeper", "Test Case Editor", "Bug Reporter"],
    "724": ["Contract Negotiator", "Executive Deal Approver", "Lead Viewer"],
    "725": ["Test Environment Access", "Test Case Editor", "Automation Script Access"],
    "726": ["HRIS Admin", "Performance Review Manager", "Employee Relations"],
    "727": ["Design System Admin", "Usability Tester", "Design Contributor"],
    "728": ["Code Reviewer", "Code Contributor", "Global Admin"],
    "729": ["Lead Viewer", "Sales Manager", "Deal Creator"],
    "730": ["Code Reviewer", "Code Contributor", "Code Viewer"],
    "734": ["Release Manager", "Global Admin", "Architecture Access"],
    "735": ["Executive Deal Approver", "Deal Creator", "Sales Manager"],
    "736": ["Prototype Access", "User Feedback Analyst", "Design Contributor"],
    "737": ["Compensation Planner", "HR Policy Editor", "Performance Review Manager"],
    "738": ["Design System Admin", "User Feedback Analyst", "Design Contributor"],
    "739": ["Prototype Access", "User Feedback Analyst", "Design Viewer"],
    "741": ["Deal Creator", "Contract Negotiator", "Lead Generator"],
    "742": ["Design Contributor", "Prototype Access", "UX Researcher"],
    "743": ["Budget Controller", "Analytics Viewer", "Campaign Viewer"],
    "744": [
        "Release Gatekeeper",
        "Automation Script Access",
        "Test Environment Access",
    ],
    "749": ["Code Viewer", "Release Manager", "Code Reviewer"],
    "751": ["Code Reviewer", "Architecture Access", "Release Manager"],
    "752": ["Campaign Viewer", "Social Media Manager", "Brand Guardian"],
    "753": ["Contract Negotiator", "Deal Creator", "Lead Generator"],
    "754": ["Lead Generator", "Executive Deal Approver", "Deal Creator"],
    "755": ["Test Case Viewer", "Global Admin", "Test Case Editor"],
    "756": ["Marketing Director", "Analytics Viewer", "Content Creator"],
    "757": ["Automation Script Access", "Test Case Editor", "Test Environment Access"],
    "758": ["Global Admin", "Code Viewer", "Code Reviewer"],
    "759": ["Brand Guardian", "Analytics Viewer", "Marketing Director"],
    "760": ["Product Analytics", "Feature Requester", "Sprint Planner"],
    "761": ["Monitoring Access", "Security Audit", "Deployment Access"],
    "762": ["Architecture Access", "Global Admin", "Release Manager"],
    "763": ["Social Media Manager", "Brand Guardian", "Budget Controller"],
    "765": ["Sales Manager", "Contract Negotiator", "Commission Reporter"],
    "766": ["Configuration Editor", "Global Admin", "Monitoring Access"],
    "767": ["Monitoring Access", "Global Admin", "Infrastructure Admin"],
    "768": ["Commission Reporter", "Lead Generator", "Deal Creator"],
    "770": ["Infrastructure Admin", "Global Admin", "Monitoring Access"],
    "771": ["Global Admin", "Test Case Editor", "Release Gatekeeper"],
    "772": ["User Feedback Analyst", "Design System Admin", "Prototype Access"],
    "773": ["Monitoring Access", "Emergency Response", "Deployment Access"],
    "774": ["Prototype Access", "Design Viewer", "User Feedback Analyst"],
    "778": ["Usability Tester", "Design Viewer", "User Feedback Analyst"],
    "779": ["Deal Creator", "Lead Viewer", "Sales Manager"],
    "781": ["Stakeholder Communicator", "Backlog Manager", "Feature Requester"],
    "782": ["Bug Reporter", "Release Gatekeeper", "Global Admin"],
    "783": ["Analytics Viewer", "Marketing Director", "Campaign Viewer"],
    "784": ["Budget Controller", "Marketing Director", "Analytics Viewer"],
    "785": ["Analytics Viewer", "Social Media Manager", "Marketing Director"],
    "786": ["Release Manager", "Code Contributor", "Code Viewer"],
    "787": ["Content Creator", "Analytics Viewer", "Budget Controller"],
    "788": ["Code Contributor", "Code Viewer", "Global Admin"],
    "789": ["Design Viewer", "Usability Tester", "User Feedback Analyst"],
    "790": ["Code Contributor", "Release Manager", "Global Admin"],
    "791": ["Emergency Response", "Security Audit", "Global Admin"],
    "792": ["HRIS Admin", "Recruitment Access", "Compensation Planner"],
    "794": ["Lead Generator", "Sales Manager", "Lead Viewer"],
    "795": ["Deployment Access", "Configuration Editor", "Infrastructure Admin"],
    "796": ["Product Analytics", "Backlog Manager", "Roadmap Viewer"],
    "798": ["Analytics Viewer", "Brand Guardian", "Marketing Director"],
    "799": ["Automation Script Access", "Test Case Viewer", "QA Lead"],
    "800": ["Code Viewer", "Release Manager", "Global Admin"],
    "802": ["Release Manager", "Code Contributor", "Global Admin"],
    "803": ["Architecture Access", "Code Reviewer", "Code Contributor"],
    "804": ["Sales Manager", "Contract Negotiator", "Commission Reporter"],
    "805": ["Backlog Manager", "Executive Reporting", "Sprint Planner"],
    "806": ["Release Manager", "Code Reviewer", "Global Admin"],
    "811": ["Budget Controller", "Content Creator", "Social Media Manager"],
    "812": ["HR Policy Editor", "Employee Directory", "Recruitment Access"],
    "813": ["Architecture Access", "Global Admin", "Code Contributor"],
    "814": ["Global Admin", "Monitoring Access", "Configuration Viewer"],
    "816": ["Campaign Viewer", "Social Media Manager", "Content Creator"],
    "818": ["UX Researcher", "Usability Tester", "Design Viewer"],
    "819": ["Recruitment Access", "Employee Directory", "HR Policy Editor"],
    "821": ["Roadmap Viewer", "Executive Reporting", "Product Analytics"],
    "823": ["Contract Negotiator", "Commission Reporter", "Lead Viewer"],
    "825": ["Content Creator", "Campaign Viewer", "Analytics Viewer"],
    "826": ["Budget Controller", "Brand Guardian", "Marketing Director"],
    "827": ["Lead Viewer", "Lead Generator", "Deal Creator"],
    "828": ["Sales Manager", "Commission Reporter", "Executive Deal Approver"],
    "830": ["Content Creator", "Budget Controller", "Brand Guardian"],
    "834": ["Design Contributor", "User Feedback Analyst", "Design Viewer"],
    "835": ["Code Reviewer", "Global Admin", "Code Contributor"],
    "836": ["Stakeholder Communicator", "Feature Requester", "Sprint Planner"],
    "837": ["Code Contributor", "Code Viewer", "Release Manager"],
    "839": ["Deal Creator", "Lead Viewer", "Commission Reporter"],
    "840": ["Code Reviewer", "Release Manager", "Architecture Access"],
    "841": ["Product Analytics", "Sprint Planner", "Roadmap Viewer"],
    "842": ["Monitoring Access", "Security Audit", "Emergency Response"],
    "844": ["Release Manager", "Code Reviewer", "Global Admin"],
    "845": ["Usability Tester", "UX Researcher", "Design Viewer"],
    "846": ["Feature Requester", "Executive Reporting", "Sprint Planner"],
    "849": ["Sales Manager", "Lead Viewer", "Lead Generator"],
    "851": ["Performance Review Manager", "Recruitment Access", "Compensation Planner"],
    "852": ["Deployment Access", "Infrastructure Admin", "Emergency Response"],
    "853": ["Infrastructure Admin", "Security Audit", "Emergency Response"],
    "854": ["Prototype Access", "User Feedback Analyst", "Design Viewer"],
    "855": ["Bug Reporter", "QA Lead", "Test Case Viewer"],
    "857": ["Configuration Editor", "Global Admin", "Configuration Viewer"],
    "860": ["Lead Viewer", "Commission Reporter", "Contract Negotiator"],
    "861": ["Usability Tester", "UX Researcher", "Design System Admin"],
    "865": ["Design Viewer", "Design Contributor", "UX Researcher"],
    "866": ["Analytics Viewer", "Social Media Manager", "Marketing Director"],
    "867": ["HR Policy Editor", "Performance Review Manager", "Employee Relations"],
    "868": ["Bug Reporter", "Global Admin", "Release Gatekeeper"],
    "869": ["Product Analytics", "Feature Requester", "Backlog Manager"],
    "870": ["Performance Review Manager", "HRIS Admin", "Employee Directory"],
    "871": ["Architecture Access", "Global Admin", "Code Viewer"],
    "872": ["Feature Requester", "Stakeholder Communicator", "Product Analytics"],
    "874": ["Lead Generator", "Lead Viewer", "Commission Reporter"],
    "877": ["Code Viewer", "Architecture Access", "Code Contributor"],
    "878": ["Product Analytics", "Backlog Manager", "Roadmap Viewer"],
    "879": ["Backlog Manager", "Product Analytics", "Feature Requester"],
    "882": ["Global Admin", "Code Reviewer", "Release Manager"],
    "884": ["Campaign Viewer", "Brand Guardian", "Social Media Manager"],
    "887": ["Infrastructure Admin", "Monitoring Access", "Security Audit"],
    "888": ["Design Viewer", "Design Contributor", "Design System Admin"],
    "889": ["Brand Guardian", "Analytics Viewer", "Budget Controller"],
    "891": ["Release Manager", "Architecture Access", "Global Admin"],
    "893": ["Design System Admin", "Usability Tester", "UX Researcher"],
    "894": ["Code Reviewer", "Global Admin", "Architecture Access"],
    "895": ["Global Admin", "Bug Reporter", "Test Case Viewer"],
    "896": ["Usability Tester", "Design Contributor", "User Feedback Analyst"],
    "897": ["Executive Deal Approver", "Commission Reporter", "Sales Manager"],
    "899": ["Marketing Director", "Social Media Manager", "Content Creator"],
    "900": ["UX Researcher", "Design Contributor", "User Feedback Analyst"],
    "902": ["Test Environment Access", "Automation Script Access", "Global Admin"],
    "904": ["UX Researcher", "Design Viewer", "Design System Admin"],
    "905": ["User Feedback Analyst", "Design System Admin", "Prototype Access"],
    "906": ["Product Analytics", "Sprint Planner", "Feature Requester"],
    "907": ["Code Viewer", "Global Admin", "Code Contributor"],
    "908": ["Stakeholder Communicator", "Product Analytics", "Roadmap Viewer"],
    "912": ["Brand Guardian", "Social Media Manager", "Budget Controller"],
    "913": ["Configuration Viewer", "Configuration Editor", "Monitoring Access"],
    "914": ["Prototype Access", "Design Viewer", "User Feedback Analyst"],
    "915": ["Stakeholder Communicator", "Sprint Planner", "Feature Requester"],
    "916": ["Lead Generator", "Contract Negotiator", "Lead Viewer"],
    "917": ["Product Analytics", "Backlog Manager", "Sprint Planner"],
    "918": ["Global Admin", "Monitoring Access", "Infrastructure Admin"],
    "919": ["Design System Admin", "User Feedback Analyst", "Usability Tester"],
    "920": ["Global Admin", "Automation Script Access", "QA Lead"],
    "923": ["Performance Review Manager", "HR Policy Editor", "HRIS Admin"],
    "927": ["Usability Tester", "Design System Admin", "UX Researcher"],
    "928": ["Stakeholder Communicator", "Sprint Planner", "Executive Reporting"],
    "930": ["Code Reviewer", "Release Manager", "Code Viewer"],
    "931": ["Configuration Viewer", "Configuration Editor", "Security Audit"],
    "932": ["Configuration Editor", "Monitoring Access", "Global Admin"],
    "933": ["Content Creator", "Marketing Director", "Analytics Viewer"],
    "936": ["Product Analytics", "Backlog Manager", "Sprint Planner"],
    "937": ["Code Reviewer", "Code Viewer", "Release Manager"],
    "938": ["Global Admin", "Monitoring Access", "Configuration Editor"],
    "939": ["User Feedback Analyst", "Design Viewer", "UX Researcher"],
    "940": ["Usability Tester", "UX Researcher", "Design Viewer"],
    "941": ["Test Case Viewer", "QA Lead", "Global Admin"],
    "942": ["Test Case Editor", "Test Environment Access", "Release Gatekeeper"],
    "943": ["Design System Admin", "Prototype Access", "UX Researcher"],
    "944": ["Configuration Editor", "Configuration Viewer", "Security Audit"],
    "945": ["Sales Manager", "Commission Reporter", "Contract Negotiator"],
    "946": ["Global Admin", "Automation Script Access", "Test Environment Access"],
    "947": ["Social Media Manager", "Content Creator", "Campaign Viewer"],
    "948": ["Release Manager", "Code Contributor", "Global Admin"],
    "950": ["Sales Manager", "Commission Reporter", "Lead Viewer"],
    "951": ["Budget Controller", "Marketing Director", "Campaign Viewer"],
    "954": ["Backlog Manager", "Product Analytics", "Stakeholder Communicator"],
    "956": ["Deployment Access", "Configuration Viewer", "Configuration Editor"],
    "957": ["Emergency Response", "Monitoring Access", "Deployment Access"],
    "958": ["Campaign Viewer", "Social Media Manager", "Marketing Director"],
    "960": ["Code Contributor", "Global Admin", "Release Manager"],
    "961": ["UX Researcher", "User Feedback Analyst", "Design Viewer"],
    "962": ["Sales Manager", "Deal Creator", "Lead Generator"],
    "964": ["Global Admin", "Release Manager", "Code Viewer"],
    "965": ["Roadmap Viewer", "Executive Reporting", "Backlog Manager"],
    "966": ["Executive Deal Approver", "Lead Generator", "Contract Negotiator"],
    "967": ["Backlog Manager", "Product Analytics", "Executive Reporting"],
    "968": ["Code Reviewer", "Architecture Access", "Release Manager"],
    "969": ["Backlog Manager", "Feature Requester", "Executive Reporting"],
    "970": ["Code Contributor", "Release Manager", "Code Viewer"],
    "971": ["Content Creator", "Marketing Director", "Budget Controller"],
    "972": ["Design System Admin", "UX Researcher", "Design Contributor"],
    "974": ["Campaign Viewer", "Brand Guardian", "Content Creator"],
    "975": ["Contract Negotiator", "Lead Viewer", "Sales Manager"],
    "976": ["Performance Review Manager", "Recruitment Access", "HRIS Admin"],
    "977": ["Monitoring Access", "Infrastructure Admin", "Configuration Editor"],
    "978": ["Configuration Viewer", "Monitoring Access", "Security Audit"],
    "979": ["QA Lead", "Global Admin", "Test Environment Access"],
    "980": ["UX Researcher", "Design Contributor", "Design Viewer"],
    "981": ["Code Reviewer", "Code Contributor", "Architecture Access"],
    "982": ["Prototype Access", "Design System Admin", "User Feedback Analyst"],
    "984": ["Configuration Editor", "Configuration Viewer", "Emergency Response"],
    "985": ["Code Reviewer", "Global Admin", "Code Contributor"],
    "988": ["Prototype Access", "Design Viewer", "Usability Tester"],
    "989": ["Sprint Planner", "Executive Reporting", "Product Analytics"],
    "990": ["Contract Negotiator", "Lead Viewer", "Sales Manager"],
    "991": ["Code Contributor", "Release Manager", "Code Viewer"],
    "993": ["Marketing Director", "Content Creator", "Brand Guardian"],
    "994": ["Release Gatekeeper", "Test Case Editor", "Automation Script Access"],
    "996": ["Global Admin", "Code Reviewer", "Architecture Access"],
    "997": ["Prototype Access", "Usability Tester", "Design Contributor"],
    "999": ["Recruitment Access", "Employee Directory", "Compensation Planner"],
    "1000": ["Analytics Viewer", "Content Creator", "Social Media Manager"],
}


class MockImpl(UserDataInterface):
    def __init__(self) -> None:
        pass

    async def get_user_data(self, user_email, **kwargs) -> dict[str, Any]:
        return {"email": "jon.doe@vandelay.com"}

    async def get_user_access(
        self, user_email: str, app_names: list[str] = [], **kwargs
    ) -> dict[str, list[UserAccess]]:
        id = user_email.split("@")[0]
        access = data[id]
        app_name = app_names[0] if len(app_names) > 0 else "mock"
        return {app_name: [UserAccess(id=a) for a in access]}
